version: '3.9'

services:
  db_principal:
    image: postgres:17.7
    container_name: spr_criminalistica_db_principal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - /home/sistema/projetos/backup_spr_criminalistica:/backup
    environment:
      - POSTGRES_DB=api_spr_db
      - POSTGRES_USER=sistema
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST:=localhost
      - POSTGRES_PORT:=5432
      - BACKUP_DIR:=/backup
      - TZ=America/Boa_Vista
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    restart: always
    networks:
      - spr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistema -d api_spr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ..
    container_name: spr_criminalistica_web
    command: gunicorn spr.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db_principal:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db_principal:5432/api_spr_db
      - TZ=America/Boa_Vista
    restart: always
    deploy:
      resources:
        limits:
          memory: 64G
    networks:
      - spr_network

volumes:
  postgres_data:
  media_volume:

networks:
  spr_network:
    driver: bridge